const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const dataDir = path.join(root, '737_Study_Finder', 'data');
const output = path.join(root, '737_Study_Finder', 'gas', 'PreparedAta24Data.gs');
const ata = process.argv[2] || '24';
const chunkSize = 20000;

const sources = {
  source_files: `source_files_ata${ata}.csv`,
  textbook_pages: `textbook_pages_ata${ata}.csv`,
  textbook_sections: `textbook_sections_ata${ata}.csv`,
  question_bank: `question_bank_ata${ata}_prepared.csv`,
  candidate_links: `candidate_links_ata${ata}.csv`,
  answer_notes: `answer_notes_ata${ata}.csv`
};

const fallbackSourceFilesCsv = [
  'source_id,source_type,ata,file_name,drive_file_id,local_path,version,note,imported_at',
  `src_sg_24_ref,study_guide_pdf,${ata},24_REF.pdf,,Study_Guide/24_REF.pdf,local,Prepared from local PDF extraction,${new Date().toISOString()}`,
  `src_question_bank_${ata},question_bank_pdf,${ata},737-800標準問題集(2012.03.13).pdf,,標準問題集/737-800標準問題集(2012.03.13).pdf,local,Prepared from local PDF extraction,${new Date().toISOString()}`,
  ''
].join('\n');

function readSourceCsv(sheetName, fileName) {
  const filePath = path.join(dataDir, fileName);
  if (fs.existsSync(filePath)) {
    return fs.readFileSync(filePath, 'utf8').replace(/^\uFEFF/, '');
  }
  if (sheetName === 'source_files') {
    return fallbackSourceFilesCsv;
  }
  throw new Error(`Missing CSV for ${sheetName}: ${filePath}`);
}

function chunkText(text) {
  const chunks = [];
  for (let index = 0; index < text.length; index += chunkSize) {
    chunks.push(text.slice(index, index + chunkSize));
  }
  return chunks;
}

function renderChunks(sheetName, csvText) {
  const chunks = chunkText(csvText);
  return [
    `    ${JSON.stringify(sheetName)}: [`,
    ...chunks.map((chunk) => `      ${JSON.stringify(chunk)},`),
    '    ]'
  ].join('\n');
}

function main() {
  const rendered = Object.entries(sources).map(([sheetName, fileName]) => {
    return renderChunks(sheetName, readSourceCsv(sheetName, fileName));
  });
  const content = [
    '// Generated by scripts/build_prepared_gas_data.js. Do not edit by hand.',
    'const PREPARED_ATA24_CSV_CHUNKS = {',
    rendered.join(',\n'),
    '};',
    '',
    'function getPreparedAta24CsvMap_() {',
    '  return Object.keys(PREPARED_ATA24_CSV_CHUNKS).reduce(function (csvMap, sheetName) {',
    '    csvMap[sheetName] = PREPARED_ATA24_CSV_CHUNKS[sheetName].join(\'\');',
    '    return csvMap;',
    '  }, {});',
    '}',
    ''
  ].join('\n');
  fs.writeFileSync(output, content, 'utf8');
  console.log(`Wrote ${path.relative(process.cwd(), output)}`);
}

main();
