const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const dataDir = path.join(root, '737_Study_Finder', 'data');
const output = path.join(root, '737_Study_Finder', 'gas', 'PreparedAtaData.gs');
const atas = process.argv.slice(2).length ? process.argv.slice(2) : ['24'];
const chunkSize = 20000;

function sourcesForAta(ata) {
  return {
    source_files: `source_files_ata${ata}.csv`,
    textbook_pages: `textbook_pages_ata${ata}.csv`,
    textbook_sections: `textbook_sections_ata${ata}.csv`,
    question_bank: `question_bank_ata${ata}_prepared.csv`,
    candidate_links: `candidate_links_ata${ata}.csv`,
    answer_notes: `answer_notes_ata${ata}.csv`
  };
}

function fallbackSourceFilesCsv(ata) {
  const studyGuideName = ata === '24' ? '24_REF.pdf' : `${ata} REF.pdf`;
  const now = new Date().toISOString();
  return [
    'source_id,source_type,ata,file_name,drive_file_id,local_path,version,note,imported_at',
    `src_sg_${ata}_ref,study_guide_pdf,${ata},${studyGuideName},,Study_Guide/${studyGuideName},local,Prepared from local PDF extraction,${now}`,
    `src_question_bank_${ata},question_bank_pdf,${ata},737-800標準問題集(2012.03.13).pdf,,標準問題集/737-800標準問題集(2012.03.13).pdf,local,Prepared from local PDF extraction,${now}`,
    ''
  ].join('\n');
}

function readSourceCsv(ata, sheetName, fileName) {
  const filePath = path.join(dataDir, fileName);
  if (fs.existsSync(filePath)) {
    return fs.readFileSync(filePath, 'utf8').replace(/^\uFEFF/, '');
  }
  if (sheetName === 'source_files') {
    return fallbackSourceFilesCsv(ata);
  }
  throw new Error(`Missing CSV for ${sheetName}: ${filePath}`);
}

function chunkText(text) {
  const chunks = [];
  for (let index = 0; index < text.length; index += chunkSize) {
    chunks.push(text.slice(index, index + chunkSize));
  }
  return chunks;
}

function renderChunks(sheetName, csvText) {
  const chunks = chunkText(csvText);
  return [
    `    ${JSON.stringify(sheetName)}: [`,
    ...chunks.map((chunk) => `      ${jsLiteral(chunk)},`),
    '    ]'
  ].join('\n');
}

function jsLiteral(value) {
  return JSON.stringify(value)
    .replace(/\u0085/g, '\\u0085')
    .replace(/\u2028/g, '\\u2028')
    .replace(/\u2029/g, '\\u2029');
}

function renderAta(ata) {
  const renderedSheets = Object.entries(sourcesForAta(ata)).map(([sheetName, fileName]) => {
    return renderChunks(sheetName, readSourceCsv(ata, sheetName, fileName));
  });
  return [
    `  ${JSON.stringify(ata)}: {`,
    renderedSheets.join(',\n'),
    '  }'
  ].join('\n');
}

function main() {
  const content = [
    '// Generated by scripts/build_prepared_gas_data.js. Do not edit by hand.',
    'const PREPARED_ATA_CSV_CHUNKS = {',
    atas.map(renderAta).join(',\n'),
    '};',
    '',
    'function getPreparedAtaList_() {',
    '  return Object.keys(PREPARED_ATA_CSV_CHUNKS).sort();',
    '}',
    '',
    'function getPreparedAtaCsvMap_(ata) {',
    "  const ataKey = String(ata || '').replace(/\\D/g, '');",
    '  const chunksBySheet = PREPARED_ATA_CSV_CHUNKS[ataKey];',
    '  if (!chunksBySheet) {',
    "    throw new Error('Prepared ATA data not found: ' + ataKey);",
    '  }',
    '  return Object.keys(chunksBySheet).reduce(function (csvMap, sheetName) {',
    "    csvMap[sheetName] = chunksBySheet[sheetName].join('');",
    '    return csvMap;',
    '  }, {});',
    '}',
    '',
    'function getPreparedAta24CsvMap_() {',
    "  return getPreparedAtaCsvMap_('24');",
    '}',
    ''
  ].join('\n');
  fs.writeFileSync(output, content, 'utf8');
  console.log(`Wrote ${path.relative(process.cwd(), output)}`);
}

main();
